### ISSUE TITLE
RSSOwl - All my collected Feeds ( since 2013 ) are lost!

### ISSUE THREAD

**Issue by StefanSchwarzFFM** [rssowl/RSSOwl#18]
Hello Team,

yesterday was the last day I saw al my collected Feeds in the RSSOwl Program.
On today's start it is asking what I like to do.

Please tell me WHERE my Original Feeds are stored and HOW I can bring them back into the Program.

Thanks a lot and with best regards,
Stefan Schwarz

**Comment by genodeftest** [comment]
Have you tried finding a database backup in your profile folder?

**Comment by StefanSchwarzFFM** [comment]
Hello it would be nice to be more specific.

There is a file called "rssowl.db.onlinebak.weekly" in the folder "C:\Users\sschwarz\.rssowl2\.metadata\.plugins\org.rssowl.core". But what should I do with this?

I am seeing the following Error in the Log-File:
>>>>>
!SESSION 2017-11-16 14:06:21.550 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_20
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86

!ENTRY org.rssowl.ui 1 0 2017-11-16 14:06:23.361
!MESSAGE RSSOwl Starting Up (RSSOwl/2.2.1.201312301314 (Windows; U; en))

!ENTRY org.eclipse.ui 4 0 2017-11-16 14:06:28.104
!MESSAGE Unable to create editor ID org.rssowl.ui.FeedView: Factory org.rssowl.ui.FeedViewFactory returned null from createElement for editor id=org.rssowl.ui.FeedView name=Business Intelligence Blog
!STACK 1
org.eclipse.ui.PartInitException: Factory org.rssowl.ui.FeedViewFactory returned null from createElement for editor id=org.rssowl.ui.FeedView name=Business Intelligence Blog
	at org.eclipse.ui.internal.EditorReference.getRestoredInput(Unknown Source)
	at org.eclipse.ui.internal.EditorReference.getEditorInput(Unknown Source)
	at org.eclipse.ui.internal.EditorReference.createPartHelper(Unknown Source)
	at org.eclipse.ui.internal.EditorReference.createPart(Unknown Source)
	at org.eclipse.ui.internal.WorkbenchPartReference.getPart(Unknown Source)
	at org.eclipse.ui.internal.EditorAreaHelper.setVisibleEditor(Unknown Source)
	at org.eclipse.ui.internal.EditorManager.setVisibleEditor(Unknown Source)
	at org.eclipse.ui.internal.EditorManager$5.runWithException(Unknown Source)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(Unknown Source)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.ui.application.WorkbenchAdvisor.openWindows(Unknown Source)
	at org.eclipse.ui.internal.Workbench$27.runWithException(Unknown Source)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(Unknown Source)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.ui.internal.Workbench.runUI(Unknown Source)
	at org.eclipse.ui.internal.Workbench.access$4(Unknown Source)
	at org.eclipse.ui.internal.Workbench$5.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Unknown Source)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Unknown Source)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(Unknown Source)
	at org.rssowl.ui.internal.Application.start(Application.java:119)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(Unknown Source)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(Unknown Source)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(Unknown Source)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(Unknown Source)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Unknown Source)
	at org.eclipse.equinox.launcher.Main.basicRun(Unknown Source)
	at org.eclipse.equinox.launcher.Main.run(Unknown Source)
!SUBENTRY 1 org.eclipse.ui 4 0 2017-11-16 14:06:28.118
!MESSAGE Factory org.rssowl.ui.FeedViewFactory returned null from createElement for editor id=org.rssowl.ui.FeedView name=Business Intelligence Blog

!ENTRY org.rssowl.core 1 0 2017-11-16 14:06:48.792
!MESSAGE RSSOwl Shutting Down (normal)
<<<<<

For me it looks like the Profile is destroyed and I do not know how to substitute the DB and come back to a working Profile with all Post collected over the Years.

What should I do next, please.

With best regards,
Stefan Schwarz

**Comment by StefanSchwarzFFM** [comment]
Hello,

okay I found a Backup-File from 09.11.2017 and being able to reconstruct.
But not all Feeds are correct, some are destroyed and some are not showing all collected Articles.

Q1) Which tool to use to read the DB?
Q2) How to protect from crash and lost happen again?

With best regards,
Stefan Schwarz

**Comment by StefanSchwarzFFM** [comment]
Hello Team,

strange Issue:
-- I am able to reconstruct most Feeds from the "Weekly Backup"
-- I delete destroyed Feeds

BUT, after a restart the Software seemed to be fresh and asking for Import again.
How can I rescue and start with the Backup and do not need to fear a restart of the Software?

With best regards,
Stefan Schwarz

**Comment by StefanSchwarzFFM** [comment]
Hello Team,

last update.
-- I need to de-install RSSOwl to get rid of some corrupted elements
-- I installed the Software new
-- I imported the "weeklyBackup"
-- I cleaned corrupted entries
-- I imported "recommended News"
-- I cleaned entries which no more exist
-- After a Restart the Software is back

Just one question:
-- With which software I am able to read the file "rssowl.db"
-- I like to rescue important older entries

Thank you and best regards,
Stefan Schwarz

**Comment by genodeftest** [comment]
> Q1) Which tool to use to read the DB?

I don't know. The database is written using db4o.

> Q2) How to protect from crash and lost happen again?

Backups. And maybe you find a backtrace in RSSOwl's logs which caused the data loss. Then have a look at the code and fix it. Bear in mind that this project is not being maintained any more and I'm not sure whether the software required for building it still exists or works. The Eclipse version RSSOwl is based on is outdated and not supported any more.

>  How can I rescue and start with the Backup and do not need to fear a restart of the Software?

I don't know.
